title: Welcome to my website!
author: Alstin Spence
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A webite about all project and acomplishments in my worklife and activities in my personal life.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  alstinspence13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

#THEME
theme: minima
